name: my_card
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento-Regular.ttf

    - family: Open Sans Reg
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: Open Sans Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf

    - family: Open Sans Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf